### ISSUE TITLE
User not found in the local mode

### ISSUE THREAD

**Issue by sworddish** [wandb/server#110] opened 2023-03-08 09:52 UTC
Previously, I deployed wandb server 0.27.0 locally without a problem. Recently, after a server crush, I have to setup wandb docker instance again. 

This time I following the steps:

❯ docker volume rm wandb
❯ pip install wandb --upgrade
❯ docker pull wandb/local:0.27.0
❯ docker run -e LOCAL_RESTORE=true --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local:0.27.0

and then I tried to manually add a new user 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/219938/223680154-d42e8f03-9f20-43d4-bbbc-89f67e426ec4.png">

I have no idea what should I do to resolve the issue and relogin again.

**Comment by sworddish** [comment] 2023-03-08 09:57
This is the 1st time I met this error, last time when I can run '/usr/local/bin/local password <account_name>' succesfully.

**Comment by thanos-wandb** [comment] 2023-03-10 11:02
Hi @sworddish thanks for reporting this issue. Could you please run `cat /vol/env/users.htpasswd` from inside the container? This will return all users emails next to a hash of respective password. Would you find any user `test@gmail.com` in that list?

**Comment by sworddish** [comment] 2023-03-13 04:23
No, I can not find.

An quick update, after I reboot the system and rerun the docker instance,
the problem sloved, but I don't know why?

thanos-wandb ***@***.***>于2023年3月10日 周五19:03写道：

**Comment by thanos-wandb** [comment] 2023-03-15 14:45
Hi @sworddish thanks for the update, glad to hear that this issue has been resolved for you after rebooting. It might have been that your signup flow was failing before because of some active sessions, or cookies. 

In older versions you could indeed add a user/password with `/usr/local/bin/local password <email>`. This command now is to be used to reset the password if the user has already registered from the App, that's the reason you were seeing `user <email> not found`. 

I hope this helps! I will now close this ticket as the issue is solved, but please feel free to reopen this if you have any other questions or issues.

**Closed by thanos-wandb** 2023-03-15 14:45 UTC
