### ISSUE TITLE
I can not upload data to local wandb server after upload data to wandb website

### ISSUE THREAD

**Issue by NieShenRuc** [wandb/server#115] opened 2023-05-20 14:17 UTC
Dear Wandb Team:
      Thank you so much for your great open source work, it's a huge help to the deep learning community, thanks!
      Because of network problems, I always use wandb offline mode, and I set up a wandb server locally. If I first upload my wandb offline file to the local server, this can be successful; but if I first upload the wandb offline file to the wandb official website, and then upload it to the local server, I will find that the official website can be uploaded successfully, but in the local server There is no mission data, why is this?
     Looking forward to your reply！

**Comment by luisbergua** [comment] 2023-05-22 13:57
Hi @NieShenRuc, thanks for reporting this! I'll try to reproduce this on my end to see if I get the same behavior as you do. Would you mind explaining to me the exact steps you are following so I can check this? Thanks!

**Comment by sydholl** [comment] 2023-05-22 13:59
Luis Bergua commented: 
Request #45937 "wandb local serve" was closed and merged into this request. Last comment in request #45937:

Hi Nieshen,

Thanks for writing in! I already responded to you in the github thread you opened so will merge this ticket into that one.

Best,
Luis

**Comment by NieShenRuc** [comment] 2023-05-23 14:21
I am so sorry, I think I make a mistake. In fact, this is the case. When my offline file is too large, I can upload it to the official server of wandb, but I cannot upload it to my local server. The performance is uploading all the time, but there is no data on the local server.

**Comment by luisbergua** [comment] 2023-05-26 11:10
Hi @NieShenRuc, thanks for clarifying! Would it be possible that the available resources of your local server are not enough? Also, could you please send `debug.log` and `debug-internal.log` for the local run? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.

**Comment by sydholl** [comment] 2023-05-26 11:11
WandB Internal User commented: 
NieShenRuc commented: 
I am so sorry, I think I make a mistake. In fact, this is the case. When my offline file is too large, I can upload it to the official server of wandb, but I cannot upload it to my local server. The performance is uploading all the time, but there is no data on the local server.

**Comment by luisbergua** [comment] 2023-05-31 09:24
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by sydholl** [comment] 2023-05-31 09:25
WandB Internal User commented: 
luisbergua commented: 
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by luisbergua** [comment] 2023-06-02 08:05
Hi @NieShenRuc, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Closed by luisbergua** 2023-06-02 08:05 UTC

**Comment by sydholl** [comment] 2023-06-12 08:51
Luis Bergua commented: 
Hi Nieshen, thanks for getting back! There're no errors in the logs you shared so I'd need to check a couple of things to figure out why you're getting this behavior:

- Could you please send the Debug Bundle of your instance? An admin of the instance can get it from the `/system-admin` page -> top right corner W&B icon -> Debug Bundle. You mentioned that the offline file is too large so would it be possible that the resources of your local server are not enough?
- Would you mind sharing a code snippet so I can try to reproduce this on my end?

**Comment by sydholl** [comment] 2023-06-13 13:17
Luis Bergua commented: 
Hi Niesehn,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,
Luis

**Comment by sydholl** [comment] 2023-06-15 10:05
Luis Bergua commented: 
Hi Niesehn, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
